name: oneDAL nightly build

on:
  schedule:
    - cron: '0 21 * * *'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_lnx:
    name: build Linux
    if: github.repository == 'icfaust/scikit-learn-intelex'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPC++
        run: .ci/env/apt.sh dpcpp
      - name: System Info
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/describe_system.sh
      - name: Make daal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target daal
      - name: Make onedal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target onedal
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_lnx
          path: ./__release_lnx_icx

  build_win:
    name: build Windows
    if: github.repository == 'icfaust/scikit-learn-intelex'
    runs-on: windows-2022

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPC++
        run: |
          $env:PATH="C:\msys64\usr\bin;$env:PATH"
          echo $env:PATH=C:\msys64\usr\bin;$env:PATH >> $env.GITHUB_ENV
          pip install cpufeature
          pacman -S -y --noconfirm zip dos2unix tree wget
          echo "Download intel DPC++ compiler"
          wget -q -O dpcpp_installer.exe https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3165d8c7-088f-410f-9723-6d8ee88d9e5b/w_dpcpp-cpp-compiler_p_2024.1.2.505_offline.exe
          echo "Unpacking DPC++ installer"
          Start-Process ".\dpcpp_installer.exe" -ArgumentList "--s --x --f oneAPI" -Wait
          echo "Installing DPC++ compiler"
          Start-Process ".\oneAPI\bootstrapper.exe" -ArgumentList "-s --eula=accept --install-dir=dpcpp" -Wait
          # This can take 20 minutes...
          echo "DPC++ install complete"
      - name: System Info
        run: |
          Start-Process ".\dpcpp\compiler\latest\env\vars.bat" -Wait
          bash .ci/scripts/describe_system.sh
      - name: Make daal
        run: |
          # & '.\dpcpp\compiler\latest\env\vars.bat'
          .\.ci\scripts\build.bat daal vc avx2
      - name: Make onedal
        run: |
          Start-Process ".\dpcpp\compiler\latest\env\vars.bat" -Wait
          .\.ci\scripts\build.bat onedal_dpc vc avx2
      - name: Archive compiler
        uses: actions/upload-artifact@v4
        with:
          name: dpcpp
          path: .\dpcpp
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_win
          path: .\__release_win_vc
