name: oneDAL nightly build

on:
  schedule:
    - cron: '0 21 * * *'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_lnx:
    name: build Linux
    if: github.repository == 'icfaust/scikit-learn-intelex'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPCPP
        run: .ci/env/apt.sh dpcpp
      - name: System Info
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/describe_system.sh
      - name: Make daal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target daal
      - name: Make onedal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target onedal
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_lnx
          path: ./__release_lnx_icx

  build_win:
    name: build Windows
    if: github.repository == 'icfaust/scikit-learn-intelex'
    runs-on: windows-2022

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPCPP
        run: |
          echo %PATH%
          echo %VS2019INSTALLDIR%
          $env:PATH="C:\msys64\usr\bin;$env:PATH"
          echo $env:PATH=C:\msys64\usr\bin;$env:PATH >> $env.GITHUB_ENV
          pip install cpufeature
          pacman -S -y --noconfirm zip dos2unix tree wget
          wget -q https://registrationcenter-download.intel.com/akdlm/IRC_NAS/3165d8c7-088f-410f-9723-6d8ee88d9e5b/w_dpcpp-cpp-compiler_p_2024.1.2.505_offline.exe
          .\w_dpcpp-cpp-compiler_p_2024.1.2.505_offline.exe" --x --f oneAPI
          dir
          dir oneAPI
      - name: System Info
        run: |
          dir
          dir dpcpp
          & '.\dpcpp\compiler\latest\env\vars.bat'
          bash .ci/scripts/describe_system.sh
      - name: Make daal
        run: |
          .\.ci\scripts\build.bat daal vc avx2
      - name: Make onedal
        run: |
          .\.ci\scripts\build.bat onedal_c vc avx2
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_win
          path: ./__release_win_vc
