name: oneDAL nightly build

on:
  schedule:
    - cron: '0 21 * * *'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: build oneDAL
    if: github.repository == 'icfaust/scikit-learn-intelex'
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
          path: ./oneDAL
      - name: Install DPCPP
        run: ./oneDAL/.ci/env/apt.sh dpcpp
      - name: System Info
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          ./oneDAL/.ci/scripts/describe_system.sh
