name: oneDAL nightly build

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: build oneDAL
    if: github.repository == 'intel/scikit-learn-intelex'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPCPP
        run: .ci/env/apt.sh dpcpp
      - name: System Info
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/describe_system.sh
      - name: Make daal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target daal
      - name: Make onedal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target onedal
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_lnx
          path: ./__release_lnx_icx
