#===============================================================================
# Copyright 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================
name: codecov
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  workflow_dispatch:
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  upload_coverage:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Codecov
    steps:
     - name: Checkout Scikit-learn-intelex
       uses: actions/checkout@v4
     - name: 'Download artifact'
       uses: actions/download-artifact@v4
       with:
          path: coverage
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          merge-multiple: true
     - name: Install codecov cli
       run: |
         curl -Os https://cli.codecov.io/latest/linux/codecov
         chmod +x codecov
     - name: Upload to codecov
       run: |
         export PR=$("$GITHUB_REF" | awk -F / '{print $3}')
         echo $PR
         if [ -n "${PR}" ]; then export PR="-P ${PR}"; fi
         echo here
         echo $PR
         export CODECOV_NAME=CI-${{ github.event.number }}-${{ github.sha }}
         export SHA=${{ github.event.workflow_run.head_sha }}
         ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -n $CODECOV_NAME -C $SHA -F github -s ./coverage $PR
